### ISSUE TITLE
Preview string in Font Dialog

### ISSUE THREAD

**Issue by khalid-hussain** [vanniktech/VNTFontListPreference#3]
Hi there,

I would like to know if it is possible to set (a) custom string(s) for the font preview dialog? I'm asking this because I wish to show the preview of non-latin fonts, in this case, Arabic. The latin file name do not accurately depict how the font will display with Arabic content.

Thanks for your time.

**Comment by vanniktech** [comment]
Hey there, that's not really possible. You would have to change some of the coding in order to set a custom string.

If you want, you can develop such a functionality and request a PR.

**Comment by vanniktech** [comment]
Has been fixed with #4
